graph LR

  %% Solid line
  A --- B

  %% Solid arrow
  A --> C

  %% Bidirectional
  A <--> K

  %% Arrow with text
  A -->|TEXT| D

  %% Dotted arrow
  A -.-> F

  %% Thick line
  A === G

  %% Thick arrow
  A ==> H

  A --o I

  A --x J