%% comments

flowchart TD 
  A[Start] ---> B{is 3 > 4?}
  B --> |Yes| C
  B --> |No| D

  subgraph id [one]
  M1["This is __a__ markdown"]
  M2["line"]
  M3["
  line1
  line2
  line3
  "]
  end

  B --> |maybe| M1
  B --> M2
  B --> M3

  C --> id