%%{init: {
  'pie': {
    'textPosition': 0.7
  },
  'theme': 'base',
  'themeVariables': {
    'pie1': '#FF6B6B',
    'pie2': '#4ECDC4',
    'pieOuterStrokeWidth': '5px',
    'pieSectionTextSize': '16px',
    'pieTitleTextSize': '22px',
    'fontFamily': 'Verdana'
  }
}}%%
pie title elements in product x
    "FRIENDS" : 5
    "FAMILY" : 95